version: '3'
services:
  db:
    image: postgres:13
    volumes:
      - task_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=task
      - POSTGRES_USER=task
      - POSTGRES_DB=task
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/task
      - SPRING_DATASOURCE_USERNAME=task
      - SPRING_DATASOURCE_PASSWORD=task
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  task_db: {}
